# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id_noticia', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('bajada', models.TextField()),
                ('fecha', models.DateField()),
                ('link_noticia', models.CharField(max_length=200)),
                ('link_recurso', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'noticias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_universidad', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'universidad',
                'managed': False,
            },
        ),
    ]
